calciatore(l_messi, rw, 91).
calciatore(k_benzema, cf, 91).
calciatore(k_benzema, st, 91).
calciatore(r_lewandowski, st, 91).
calciatore(k_de_bruyne, cm, 91).
calciatore(k_de_bruyne, cam, 91).
calciatore(k_mbappe, st, 91).
calciatore(k_mbappe, lw, 91).
calciatore(m_salah, rw, 90).
calciatore(t_courtois, gk, 90).
calciatore(m_neuer, gk, 90).
calciatore(cristiano_ronaldo, st, 90).
calciatore(v_van_dijk, cb, 90).
calciatore(h_kane, st, 89).
calciatore(neymar_jr, lw, 89).
calciatore(h_son, lw, 89).
calciatore(h_son, lm, 89).
calciatore(casemiro, cdm, 89).
calciatore(j_oblak, gk, 89).
calciatore(s_mane, lm, 89).
calciatore(s_mane, cf, 89).
calciatore(ederson, gk, 89).
calciatore(j_kimmich, cdm, 89).
calciatore(j_kimmich, rb, 89).
calciatore(alisson, gk, 89).
calciatore(n_kante, cdm, 89).
calciatore(n_kante, cm, 89).
calciatore(ruben_dias, cb, 88).
calciatore(e_haaland, st, 88).
calciatore(g_donnarumma, gk, 88).
calciatore(bernardo_silva, cam, 88).
calciatore(bernardo_silva, cm, 88).
calciatore(joao_cancelo, lb, 88).
calciatore(joao_cancelo, rb, 88).
calciatore(marquinhos, cb, 88).
calciatore(k_navas, gk, 88).
calciatore(m_ter_stegen, gk, 88).
calciatore(t_kroos, cm, 88).
calciatore(l_modric, cm, 88).
calciatore(a_rudiger, cb, 87).
calciatore(rodri, cdm, 87).
calciatore(fabinho, cdm, 87).
calciatore(fabinho, cb, 87).
calciatore(h_lloris, gk, 87).
calciatore(t_muller, cam, 87).
calciatore(t_muller, cf, 87).
calciatore(de_gea, gk, 87).
calciatore(m_verratti, cm, 87).
calciatore(m_verratti, cam, 87).
calciatore(m_maignan, gk, 87).
calciatore(t_alexander_arnold, rb, 87).
calciatore(a_robertson, lb, 87).
calciatore(k_koulibaly, cb, 87).
calciatore(l_goretzka, cm, 87).
calciatore(l_goretzka, cdm, 87).
calciatore(f_de_jong, cm, 87).
calciatore(thiago, cm, 86).
calciatore(c_immobile, st, 86).
calciatore(r_lukaku, st, 86).
calciatore(d_alaba, cb, 86).
calciatore(r_sterling, lw, 86).
calciatore(r_sterling, rw, 86).
calciatore(r_mahrez, rw, 86).
calciatore(r_mahrez, rm, 86).
calciatore(p_dybala, cf, 86).
calciatore(p_dybala, cam, 86).
calciatore(thiago_silva, cb, 86).
calciatore(w_szczesny, gk, 86).
calciatore(k_trapp, gk, 86).
calciatore(bruno_fernandes, cam, 86).
calciatore(bruno_fernandes, cm, 86).
calciatore(parejo, cm, 86).
calciatore(a_laporte, cb, 86).
calciatore(k_coman, lm, 86).
calciatore(m_brozovic, cdm, 86).
calciatore(m_brozovic, cm, 86).
calciatore(n_barella, cm, 86).
calciatore(l_martinez, st, 86).
calciatore(m_skriniar, cb, 86).
calciatore(c_nkunku, cf, 86).
calciatore(c_nkunku, cam, 86).
calciatore(c_nkunku, st, 86).
calciatore(e_mendy, gk, 86).
calciatore(vinicius_jr, lw, 86).
calciatore(s_milinkovic_savic, cm, 86).
calciatore(n_sule, cb, 85).
calciatore(n_sule, rb, 85).
calciatore(n_fekir, cam, 85).
calciatore(s_gnabry, rm, 85).
calciatore(i_gundogan, cm, 85).
calciatore(i_gundogan, cdm, 85).
calciatore(k_walker, rb, 85).
calciatore(p_aubameyang, st, 85).
calciatore(jordi_alba, lb, 85).
calciatore(sergio_busquets, cdm, 85).
calciatore(iago_aspas, st, 85).
calciatore(p_pogba, cm, 85).
calciatore(p_pogba, cdm, 85).
calciatore(p_pogba, lm, 85).
calciatore(m_depay, cf, 85).
calciatore(m_depay, st, 85).
calciatore(m_depay, lw, 85).
calciatore(jorginho, cm, 85).
calciatore(m_acuna, lb, 85).
calciatore(gerard_moreno, st, 85).
calciatore(y_carrasco, lm, 85).
calciatore(f_kostic, lm, 85).
calciatore(f_kostic, lwb, 85).
calciatore(j_vardy, st, 85).
calciatore(pedri, cm, 85).
calciatore(p_foden, lw, 85).
calciatore(p_foden, cf, 85).
calciatore(p_foden, cam, 85).
calciatore(m_de_ligt, cb, 85).
calciatore(p_schick, st, 85).
calciatore(t_hernandez, lb, 85).
calciatore(diogo_jota, cf, 85).
calciatore(diogo_jota, lw, 85).
calciatore(p_gulacsi, gk, 85).
calciatore(y_sommer, gk, 85).
calciatore(m_reus, cam, 85).
calciatore(m_reus, cf, 85).
calciatore(m_reus, rm, 85).
calciatore(l_hernandez, cb, 84).
calciatore(l_hernandez, lb, 84).
calciatore(sergio_ramos, cb, 84).
calciatore(a_gomez, cam, 84).
calciatore(a_gomez, lw, 84).
calciatore(s_handanovic, gk, 84).
calciatore(d_mertens, cf, 84).
calciatore(d_mertens, st, 84).
calciatore(d_mertens, cam, 84).
calciatore(l_suarez, st, 84).
calciatore(d_tadic, lw, 84).
calciatore(d_tadic, cf, 84).
calciatore(d_tadic, cam, 84).
calciatore(d_berardi, rm, 84).
calciatore(d_berardi, rw, 84).
calciatore(t_partey, cdm, 84).
calciatore(t_partey, cm, 84).
