calciatore('l_messi', 91, 'argentina', 'paris_saint_germain', 30, 'cam').
calciatore('k_benzema', 91, 'france', 'real_madrid_cf', 9, 'cf').
calciatore('r_lewandowski', 91, 'poland', 'fc_barcelona', 9, 'st').
calciatore('k_de_bruyne', 91, 'belgium', 'manchester_city', 17, 'cm').
calciatore('k_mbappe', 91, 'france', 'paris_saint_germain', 7, 'st').
calciatore('m_salah', 90, 'egypt', 'liverpool', 11, 'rw').
calciatore('t_courtois', 90, 'belgium', 'real_madrid_cf', 1, 'gk').
calciatore('m_neuer', 90, 'germany', 'fc_bayern_munchen', 1, 'gk').
calciatore('cristiano_ronaldo', 90, 'portugal', 'manchester_united', 7, 'st').
calciatore('v_van_dijk', 90, 'netherlands', 'liverpool', 4, 'cb').
calciatore('h_kane', 89, 'england', 'tottenham_hotspur', 10, 'st').
calciatore('neymar_jr', 89, 'brazil', 'paris_saint_germain', 10, 'lw').
calciatore('h_son', 89, 'korea_republic', 'tottenham_hotspur', 7, 'lw').
calciatore('casemiro', 89, 'brazil', 'manchester_united', 18, 'cdm').
calciatore('j_oblak', 89, 'slovenia', 'atletico_de_madrid', 13, 'gk').
calciatore('s_mane', 89, 'senegal', 'fc_bayern_munchen', 17, 'lm').
calciatore('ederson', 89, 'brazil', 'manchester_city', 31, 'gk').
calciatore('j_kimmich', 89, 'germany', 'fc_bayern_munchen', 6, 'cdm').
calciatore('alisson', 89, 'brazil', 'liverpool', 1, 'gk').
calciatore('n_kante', 89, 'france', 'chelsea', 7, 'cdm').
calciatore('ruben_dias', 88, 'portugal', 'manchester_city', 3, 'cb').
calciatore('e_haaland', 88, 'norway', 'manchester_city', 9, 'st').
calciatore('g_donnarumma', 88, 'italy', 'paris_saint_germain', 99, 'gk').
calciatore('bernardo_silva', 88, 'portugal', 'manchester_city', 20, 'cam').
calciatore('joao_cancelo', 88, 'portugal', 'manchester_city', 7, 'lb').
calciatore('marquinhos', 88, 'brazil', 'paris_saint_germain', 5, 'cb').
calciatore('k_navas', 88, 'costa_rica', 'paris_saint_germain', 1, 'gk').
calciatore('m_ter_stegen', 88, 'germany', 'fc_barcelona', 1, 'gk').
calciatore('t_kroos', 88, 'germany', 'real_madrid_cf', 8, 'cm').
calciatore('l_modric', 88, 'croatia', 'real_madrid_cf', 10, 'cm').
calciatore('a_rudiger', 87, 'germany', 'real_madrid_cf', 22, 'cb').
calciatore('rodri', 87, 'spain', 'manchester_city', 16, 'cdm').
calciatore('fabinho', 87, 'brazil', 'liverpool', 3, 'cdm').
calciatore('h_lloris', 87, 'france', 'tottenham_hotspur', 1, 'gk').
calciatore('t_muller', 87, 'germany', 'fc_bayern_munchen', 25, 'cam').
calciatore('de_gea', 87, 'spain', 'manchester_united', 1, 'gk').
calciatore('m_verratti', 87, 'italy', 'paris_saint_germain', 6, 'cm').
calciatore('m_maignan', 87, 'france', 'ac_milan', 16, 'gk').
calciatore('t_alexander_arnold', 87, 'england', 'liverpool', 66, 'cm').
calciatore('a_robertson', 87, 'scotland', 'liverpool', 26, 'lb').
calciatore('k_koulibaly', 87, 'senegal', 'chelsea', 26, 'cb').
calciatore('l_goretzka', 87, 'germany', 'fc_bayern_munchen', 8, 'cm').
calciatore('f_de_jong', 87, 'netherlands', 'fc_barcelona', 21, 'cm').
calciatore('thiago', 86, 'spain', 'liverpool', 6, 'cm').
calciatore('c_immobile', 86, 'italy', 'lazio', 17, 'st').
calciatore('r_lukaku', 86, 'belgium', 'inter', 90, 'st').
calciatore('d_alaba', 86, 'austria', 'real_madrid_cf', 4, 'cb').
calciatore('r_sterling', 86, 'england', 'chelsea', 17, 'lw').
calciatore('r_mahrez', 86, 'algeria', 'manchester_city', 26, 'rw').
calciatore('p_dybala', 86, 'argentina', 'roma', 21, 'cam').
calciatore('thiago_silva', 86, 'brazil', 'chelsea', 6, 'cb').
calciatore('w_szczesny', 86, 'poland', 'juventus', 1, 'gk').
calciatore('k_trapp', 86, 'germany', 'eintracht_frankfurt', 1, 'gk').
calciatore('bruno_fernandes', 86, 'portugal', 'manchester_united', 8, 'cam').
calciatore('parejo', 86, 'spain', 'villarreal_cf', 10, 'cm').
calciatore('a_laporte', 86, 'spain', 'manchester_city', 14, 'cb').
calciatore('k_coman', 86, 'france', 'fc_bayern_munchen', 11, 'lm').
calciatore('m_brozovic', 86, 'croatia', 'inter', 77, 'cdm').
calciatore('n_barella', 86, 'italy', 'inter', 23, 'cm').
calciatore('l_martinez', 86, 'argentina', 'inter', 10, 'st').
calciatore('m_skriniar', 86, 'slovakia', 'inter', 37, 'cb').
calciatore('c_nkunku', 86, 'france', 'rb_leipzig', 18, 'cam').
calciatore('e_mendy', 86, 'senegal', 'chelsea', 16, 'gk').
calciatore('vinicius_jr', 86, 'brazil', 'real_madrid_cf', 20, 'lw').
calciatore('s_milinkovic_savic', 86, 'serbia', 'lazio', 21, 'cm').
calciatore('n_sule', 85, 'germany', 'borussia_dortmund', 25, 'cb').
calciatore('n_fekir', 85, 'france', 'real_betis_balompie', 8, 'cam').
calciatore('s_gnabry', 85, 'germany', 'fc_bayern_munchen', 7, 'rm').
calciatore('i_gundogan', 85, 'germany', 'manchester_city', 8, 'cm').
calciatore('k_walker', 85, 'england', 'manchester_city', 2, 'rb').
calciatore('p_aubameyang', 85, 'gabon', 'chelsea', 9, 'st').
calciatore('jordi_alba', 85, 'spain', 'fc_barcelona', 18, 'lb').
calciatore('sergio_busquets', 85, 'spain', 'fc_barcelona', 5, 'cdm').
calciatore('iago_aspas', 85, 'spain', 'rc_celta_de_vigo', 10, 'st').
calciatore('p_pogba', 85, 'france', 'juventus', 10, 'cm').
calciatore('m_depay', 85, 'netherlands', 'fc_barcelona', 14, 'cf').
calciatore('jorginho', 85, 'italy', 'chelsea', 5, 'cm').
calciatore('m_acuna', 85, 'argentina', 'sevilla_fc', 19, 'lb').
calciatore('gerard_moreno', 85, 'spain', 'villarreal_cf', 7, 'st').
calciatore('y_carrasco', 85, 'belgium', 'atletico_de_madrid', 21, 'lm').
calciatore('f_kostic', 85, 'serbia', 'juventus', 17, 'lm').
calciatore('j_vardy', 85, 'england', 'leicester_city', 9, 'st').
calciatore('pedri', 85, 'spain', 'fc_barcelona', 8, 'cm').
calciatore('p_foden', 85, 'england', 'manchester_city', 47, 'cam').
calciatore('m_de_ligt', 85, 'netherlands', 'fc_bayern_munchen', 4, 'cb').
calciatore('p_schick', 85, 'czech_republic', 'bayer_04_leverkusen', 14, 'st').
calciatore('t_hernandez', 85, 'france', 'ac_milan', 19, 'lwb').
calciatore('diogo_jota', 85, 'portugal', 'liverpool', 20, 'st').
calciatore('p_gulacsi', 85, 'hungary', 'rb_leipzig', 1, 'gk').
calciatore('y_sommer', 85, 'switzerland', 'borussia_monchengladbach', 1, 'gk').
calciatore('m_reus', 85, 'germany', 'borussia_dortmund', 11, 'cam').
calciatore('l_hernandez', 84, 'france', 'fc_bayern_munchen', 21, 'cb').
calciatore('sergio_ramos', 84, 'spain', 'paris_saint_germain', 4, 'cb').
calciatore('a_gomez', 84, 'argentina', 'sevilla_fc', 24, 'cam').
calciatore('s_handanovic', 84, 'slovenia', 'inter', 1, 'gk').
calciatore('d_mertens', 84, 'belgium', 'galatasaray_sk', 10, 'cf').
calciatore('l_suarez', 84, 'uruguay', 'club_nacional_de_football', 9, 'st').
calciatore('d_tadic', 84, 'serbia', 'ajax', 10, 'lw').
calciatore('d_berardi', 84, 'italy', 'us_sassuolo_calcio', 10, 'rm').
calciatore('t_partey', 84, 'ghana', 'arsenal', 5, 'cdm').
calciatore('y_bounou', 84, 'morocco', 'sevilla_fc', 13, 'gk').
calciatore('h_calhanoglu', 84, 'turkey', 'inter', 20, 'cm').
calciatore('m_kovacic', 84, 'croatia', 'chelsea', 8, 'cm').
calciatore('j_grealish', 84, 'england', 'manchester_city', 10, 'lw').
calciatore('carvajal', 84, 'spain', 'real_madrid_cf', 2, 'rb').
calciatore('s_savic', 84, 'montenegro', 'atletico_de_madrid', 15, 'cb').
calciatore('e_martinez', 84, 'argentina', 'aston_villa', 1, 'gk').
calciatore('r_varane', 84, 'france', 'manchester_united', 19, 'cb').
calciatore('w_ben_yedder', 84, 'france', 'as_monaco', 10, 'cf').
calciatore('l_insigne', 84, 'italy', 'toronto_fc', 24, 'cam').
calciatore('m_hummels', 84, 'germany', 'borussia_dortmund', 15, 'cb').
calciatore('s_de_vrij', 84, 'netherlands', 'inter', 6, 'cb').
calciatore('j_matip', 84, 'cameroon', 'liverpool', 32, 'cb').
calciatore('k_casteels', 84, 'belgium', 'vfl_wolfsburg', 1, 'gk').
calciatore('canales', 84, 'spain', 'real_betis_balompie', 10, 'rm').
calciatore('muniain', 84, 'spain', 'athletic_club_de_bilbao', 10, 'lm').
calciatore('k_trippier', 84, 'england', 'newcastle_united', 2, 'rb').
calciatore('l_bonucci', 84, 'italy', 'juventus', 19, 'cb').
calciatore('a_di_maria', 84, 'argentina', 'juventus', 22, 'rw').
calciatore('e_hazard', 84, 'belgium', 'real_madrid_cf', 7, 'lw').
calciatore('i_perisic', 84, 'croatia', 'tottenham_hotspur', 14, 'lm').
calciatore('e_dzeko', 84, 'bosnia_and_herzegovina', 'inter', 9, 'st').
calciatore('g_chiellini', 84, 'italy', 'los_angeles_fc', 14, 'cb').
calciatore('r_de_paul', 84, 'argentina', 'atletico_de_madrid', 5, 'cm').
calciatore('j_bellingham', 84, 'england', 'borussia_dortmund', 22, 'cm').
calciatore('f_chiesa', 84, 'italy', 'juventus', 7, 'rm').
calciatore('m_diaby', 84, 'france', 'bayer_04_leverkusen', 19, 'rm').
calciatore('j_tartt', 84, 'england', 'afc_richmond', 9, 'cam').
calciatore('rafael_leao', 84, 'portugal', 'ac_milan', 17, 'lw').
calciatore('j_kounde', 84, 'france', 'fc_barcelona', 23, 'cb').
calciatore('y_tielemans', 84, 'belgium', 'leicester_city', 8, 'cm').
calciatore('s_tonali', 84, 'italy', 'ac_milan', 8, 'cdm').
calciatore('l_diaz', 84, 'colombia', 'liverpool', 23, 'rm').
calciatore('eder_militao', 84, 'brazil', 'real_madrid_cf', 3, 'cb').
calciatore('f_valverde', 84, 'uruguay', 'real_madrid_cf', 15, 'cm').
calciatore('l_sane', 84, 'germany', 'fc_bayern_munchen', 10, 'lm').
calciatore('r_james', 84, 'england', 'chelsea', 24, 'rwb').
calciatore('a_bastoni', 84, 'italy', 'inter', 95, 'cb').
calciatore('k_havertz', 84, 'germany', 'chelsea', 29, 'cam').
calciatore('joao_felix', 84, 'portugal', 'atletico_de_madrid', 7, 'cam').
calciatore('a_hakimi', 84, 'morocco', 'paris_saint_germain', 2, 'rb').
calciatore('a_davies', 84, 'canada', 'fc_bayern_munchen', 19, 'lm').
calciatore('d_rice', 84, 'england', 'west_ham_united', 41, 'cdm').
calciatore('m_mount', 84, 'england', 'chelsea', 19, 'cam').
calciatore('j_sancho', 84, 'england', 'manchester_united', 25, 'cam').
calciatore('f_tomori', 84, 'england', 'ac_milan', 23, 'cb').
calciatore('f_kessie', 84, 'cote_divoire', 'fc_barcelona', 19, 'cdm').
calciatore('oyarzabal', 84, 'spain', 'real_sociedad', 10, 'lw').
calciatore('l_pellegrini', 84, 'italy', 'roma', 7, 'cam').
calciatore('w_ndidi', 84, 'nigeria', 'leicester_city', 25, 'cb').
calciatore('marcos_llorente', 84, 'spain', 'atletico_de_madrid', 14, 'cam').
calciatore('m_odegaard', 84, 'norway', 'arsenal', 8, 'cam').
calciatore('d_vlahovic', 84, 'serbia', 'juventus', 9, 'st').
calciatore('diego_carlos', 83, 'brazil', 'aston_villa', 3, 'cb').
calciatore('angelino', 83, 'spain', 'tsg_hoffenheim', 11, 'lm').
calciatore('o_dembele', 83, 'france', 'fc_barcelona', 7, 'lm').
calciatore('marco_asensio', 83, 'spain', 'real_madrid_cf', 11, 'rw').
calciatore('ruben_neves', 83, 'portugal', 'wolverhampton_wanderers', 8, 'cm').
calciatore('merino', 83, 'spain', 'real_sociedad', 8, 'cm').
calciatore('k_laimer', 83, 'austria', 'rb_leipzig', 27, 'cdm').
calciatore('p_kimpembe', 83, 'france', 'paris_saint_germain', 3, 'cb').
calciatore('fabian', 83, 'spain', 'paris_saint_germain', 8, 'cm').
calciatore('f_mendy', 83, 'france', 'real_madrid_cf', 23, 'lb').
calciatore('ronaldo_cabrais', 83, 'brazil', 'palmeiras', 10, 'rm').
calciatore('gabriel_jesus', 83, 'brazil', 'arsenal', 9, 'st').
calciatore('unai_simon', 83, 'spain', 'athletic_club_de_bilbao', 1, 'gk').
calciatore('v_osimhen', 83, 'nigeria', 'napoli', 9, 'st').
calciatore('p_hojbjerg', 83, 'denmark', 'tottenham_hotspur', 5, 'cdm').
calciatore('c_romero', 83, 'argentina', 'tottenham_hotspur', 17, 'cb').
calciatore('raphinha', 83, 'brazil', 'fc_barcelona', 22, 'lm').
calciatore('carlos_soler', 83, 'spain', 'paris_saint_germain', 28, 'cm').
calciatore('g_kobel', 83, 'switzerland', 'borussia_dortmund', 1, 'gk').
calciatore('pau_torres', 83, 'spain', 'villarreal_cf', 4, 'cb').
calciatore('c_gakpo', 83, 'netherlands', 'psv', 11, 'rm').
calciatore('r_araujo', 83, 'uruguay', 'fc_barcelona', 4, 'cb').
calciatore('r_kent', 83, 'england', 'afc_richmond', 6, 'cdm').
calciatore('d_zapata', 83, 'colombia', 'atalanta', 91, 'st').
calciatore('a_correa', 83, 'argentina', 'atletico_de_madrid', 10, 'cf').
calciatore('j_gimenez', 83, 'uruguay', 'atletico_de_madrid', 2, 'cb').
calciatore('t_lemar', 83, 'france', 'atletico_de_madrid', 11, 'cam').
calciatore('bremer', 83, 'brazil', 'juventus', 3, 'cb').
calciatore('j_cuadrado', 83, 'colombia', 'juventus', 11, 'rb').
calciatore('p_zielinski', 83, 'poland', 'napoli', 20, 'cam').
calciatore('jesus_navas', 83, 'spain', 'sevilla_fc', 16, 'rb').
calciatore('pique', 83, 'spain', 'fc_barcelona', 3, 'cb').
calciatore('k_schmeichel', 83, 'denmark', 'ogc_nice', 1, 'gk').
calciatore('j_henderson', 83, 'england', 'liverpool', 14, 'cm').
calciatore('fernando', 83, 'brazil', 'sevilla_fc', 20, 'cdm').
calciatore('l_hradecky', 83, 'finland', 'bayer_04_leverkusen', 1, 'gk').
calciatore('david_silva', 83, 'spain', 'real_sociedad', 21, 'cam').
calciatore('o_baumann', 83, 'germany', 'tsg_hoffenheim', 1, 'gk').
calciatore('a_griezmann', 83, 'france', 'atletico_de_madrid', 8, 'cam').
calciatore('luis_alberto', 83, 'spain', 'lazio', 10, 'cm').
calciatore('roberto_firmino', 83, 'brazil', 'liverpool', 9, 'cf').
calciatore('j_stones', 83, 'england', 'manchester_city', 5, 'cb').
calciatore('h_ziyech', 83, 'morocco', 'chelsea', 22, 'rw').
calciatore('koke', 83, 'spain', 'atletico_de_madrid', 6, 'cm').
calciatore('ricardo_pereira', 83, 'portugal', 'leicester_city', 21, 'rb').
calciatore('j_maddison', 82, 'england', 'leicester_city', 10, 'cam').
calciatore('g_rulli', 82, 'argentina', 'villarreal_cf', 13, 'gk').
calciatore('a_kramaric', 82, 'croatia', 'tsg_hoffenheim', 27, 'cf').
calciatore('rafa', 82, 'portugal', 'sl_benfica', 27, 'rw').
calciatore('g_di_lorenzo', 82, 'italy', 'napoli', 22, 'rb').
calciatore('david_soria', 82, 'spain', 'getafe_cf', 13, 'gk').
calciatore('m_locatelli', 82, 'italy', 'juventus', 27, 'cm').
calciatore('r_gosens', 82, 'germany', 'inter', 8, 'lwb').
calciatore('goncalo_guedes', 82, 'portugal', 'wolverhampton_wanderers', 17, 'st').
calciatore('j_tah', 82, 'germany', 'bayer_04_leverkusen', 4, 'cb').
calciatore('a_christensen', 82, 'denmark', 'fc_barcelona', 15, 'cb').
calciatore('e_can', 82, 'germany', 'borussia_dortmund', 23, 'cb').
calciatore('anderson_talisca', 82, 'brazil', 'al_nassr', 94, 'cf').
calciatore('j_brandt', 82, 'germany', 'borussia_dortmund', 19, 'cam').
calciatore('t_werner', 82, 'germany', 'rb_leipzig', 11, 'st').
calciatore('gaya', 82, 'spain', 'valencia_cf', 14, 'lb').
calciatore('otavio', 82, 'portugal', 'fc_porto', 25, 'rm').
calciatore('grimaldo', 82, 'spain', 'sl_benfica', 3, 'lb').
calciatore('r_guerreiro', 82, 'portugal', 'borussia_dortmund', 13, 'cam').
calciatore('a_onana', 82, 'cameroon', 'inter', 24, 'gk').
calciatore('m_ginter', 82, 'germany', 'sport_club_freiburg', 28, 'cb').
calciatore('s_haller', 82, 'cote_divoire', 'borussia_dortmund', 9, 'st').
calciatore('aritz_elustondo', 82, 'spain', 'real_sociedad', 6, 'cb').
calciatore('t_abraham', 82, 'england', 'roma', 9, 'st').
calciatore('i_bennacer', 82, 'algeria', 'ac_milan', 4, 'cm').
calciatore('alex_remiro', 82, 'spain', 'real_sociedad', 1, 'gk').
calciatore('d_rojas', 82, 'mexico', 'afc_richmond', 14, 'st').
calciatore('f_wirtz', 82, 'germany', 'bayer_04_leverkusen', 27, 'cam').
calciatore('antony', 82, 'brazil', 'manchester_united', 21, 'lm').
calciatore('d_nunez', 82, 'uruguay', 'liverpool', 27, 'st').
calciatore('n_schlotterbeck', 82, 'germany', 'borussia_dortmund', 4, 'cb').
calciatore('b_saka', 82, 'england', 'arsenal', 7, 'lm').
calciatore('dani_olmo', 82, 'spain', 'rb_leipzig', 7, 'cam').
calciatore('a_tchouameni', 82, 'france', 'real_madrid_cf', 18, 'cdm').
calciatore('ferran_torres', 82, 'spain', 'fc_barcelona', 11, 'lw').
calciatore('n_mazraoui', 82, 'morocco', 'fc_bayern_munchen', 40, 'rm').
calciatore('a_danjuma', 82, 'netherlands', 'villarreal_cf', 9, 'lm').
calciatore('a_ramsdale', 82, 'england', 'arsenal', 32, 'gk').
calciatore('lucas_paqueta', 82, 'brazil', 'west_ham_united', 11, 'cam').
calciatore('d_dumfries', 82, 'netherlands', 'inter', 2, 'rwb').
calciatore('r_malinovskyi', 82, 'ukraine', 'atalanta', 18, 'cf').
calciatore('r_jimenez', 82, 'mexico', 'wolverhampton_wanderers', 9, 'st').
calciatore('josue_chiamulera', 82, 'brazil', 'club_athletico_paranaense', 6, 'cb').
calciatore('lucas_mantela', 82, 'brazil', 'palmeiras', 1, 'gk').
calciatore('b_chilwell', 82, 'england', 'chelsea', 21, 'lwb').
calciatore('andre_silva', 82, 'portugal', 'rb_leipzig', 19, 'st').
calciatore('c_pulisic', 82, 'united_states', 'chelsea', 10, 'rm').
calciatore('j_pickford', 82, 'england', 'everton', 1, 'gk').
calciatore('sergi_darder', 82, 'spain', 'rcd_espanyol_de_barcelona', 10, 'cm').
calciatore('w_orban', 82, 'hungary', 'rb_leipzig', 4, 'cb').
calciatore('i_gueye', 82, 'senegal', 'everton', 27, 'cdm').
calciatore('z_ibrahimovic', 82, 'sweden', 'ac_milan', 11, 'st').
calciatore('inigo_martinez', 82, 'spain', 'athletic_club_de_bilbao', 4, 'cb').
calciatore('l_fabianski', 82, 'poland', 'west_ham_united', 1, 'gk').
calciatore('i_rakitic', 82, 'croatia', 'sevilla_fc', 10, 'cm').
calciatore('d_payet', 82, 'france', 'olympique_de_marseille', 10, 'cam').
calciatore('rui_patricio', 82, 'portugal', 'roma', 1, 'gk').
calciatore('o_giroud', 82, 'france', 'ac_milan', 9, 'st').
calciatore('s_kjaer', 82, 'denmark', 'ac_milan', 24, 'cb').
calciatore('yuri_berchiche', 82, 'spain', 'athletic_club_de_bilbao', 17, 'lb').
calciatore('t_alderweireld', 82, 'belgium', 'royal_antwerp_fc', 23, 'cb').
calciatore('m_arnautovic', 82, 'austria', 'bologna', 9, 'st').
calciatore('azpilicueta', 82, 'spain', 'chelsea', 28, 'cb').
calciatore('coutinho', 82, 'brazil', 'aston_villa', 23, 'cam').
calciatore('c_eriksen', 82, 'denmark', 'manchester_united', 14, 'cm').
calciatore('raul_albiol', 82, 'spain', 'villarreal_cf', 3, 'cb').
calciatore('s_coates', 82, 'uruguay', 'sporting_cp', 4, 'cb').
calciatore('l_digne', 82, 'france', 'aston_villa', 27, 'lb').
calciatore('isco', 82, 'spain', 'sevilla_fc', 22, 'cam').
calciatore('g_kondogbia', 82, 'central_african_republic', 'atletico_de_madrid', 4, 'cdm').
calciatore('gabriel_paulista', 82, 'brazil', 'valencia_cf', 5, 'cb').
calciatore('nacho_fernandez', 82, 'spain', 'real_madrid_cf', 6, 'cb').
calciatore('k_volland', 82, 'germany', 'as_monaco', 31, 'st').
calciatore('l_spinazzola', 82, 'italy', 'roma', 37, 'lwb').
calciatore('s_berghuis', 82, 'netherlands', 'ajax', 23, 'cam').
calciatore('a_lopes', 82, 'portugal', 'olympique_lyonnais', 1, 'gk').
calciatore('l_muriel', 82, 'colombia', 'atalanta', 9, 'st').
calciatore('w_zaha', 82, 'cote_divoire', 'crystal_palace', 11, 'lw').
calciatore('f_acerbi', 82, 'italy', 'inter', 15, 'cb').
calciatore('e_ndicka', 81, 'france', 'eintracht_frankfurt', 2, 'cb').
calciatore('t_soucek', 81, 'czech_republic', 'west_ham_united', 28, 'cb').
calciatore('a_barak', 81, 'czech_republic', 'fiorentina', 72, 'cam').
calciatore('m_terrier', 81, 'france', 'stade_rennais_fc', 7, 'st').
calciatore('d_raum', 81, 'germany', 'rb_leipzig', 22, 'lwb').
calciatore('y_bissouma', 81, 'mali', 'tottenham_hotspur', 38, 'cdm').
calciatore('a_areola', 81, 'france', 'west_ham_united', 13, 'gk').
calciatore('i_sangare', 81, 'cote_divoire', 'psv', 6, 'cdm').
calciatore('j_corona', 81, 'mexico', 'sevilla_fc', 9, 'rw').
calciatore('t_delaney', 81, 'denmark', 'sevilla_fc', 18, 'cdm').
calciatore('a_lacazette', 81, 'france', 'olympique_lyonnais', 91, 'st').
calciatore('n_zaniolo', 81, 'italy', 'roma', 22, 'cam').
calciatore('neto', 81, 'brazil', 'afc_bournemouth', 13, 'gk').
calciatore('i_konate', 81, 'france', 'liverpool', 5, 'cb').
calciatore('pedro_porro', 81, 'spain', 'sporting_cp', 24, 'rwb').
calciatore('cucurella', 81, 'spain', 'chelsea', 32, 'lwb').
calciatore('l_martinez', 81, 'argentina', 'manchester_united', 6, 'cdm').
calciatore('matheus_cunha', 81, 'brazil', 'atletico_de_madrid', 9, 'cam').
calciatore('pedro_goncalves', 81, 'portugal', 'sporting_cp', 28, 'cam').
calciatore('m_taremi', 81, 'iran', 'fc_porto', 9, 'st').
calciatore('rodrygo', 81, 'brazil', 'real_madrid_cf', 21, 'rm').
calciatore('e_tapsoba', 81, 'burkina_faso', 'bayer_04_leverkusen', 12, 'cb').
calciatore('d_kulusevski', 81, 'sweden', 'tottenham_hotspur', 21, 'cam').
calciatore('bruno_guimaraes', 81, 'brazil', 'newcastle_united', 39, 'cm').
calciatore('j_gvardiol', 81, 'croatia', 'rb_leipzig', 32, 'cb').
calciatore('j_musiala', 81, 'germany', 'fc_bayern_munchen', 42, 'cam').
calciatore('s_obisanya', 81, 'nigeria', 'afc_richmond', 24, 'rm').
calciatore('pablo_sarabia', 81, 'spain', 'paris_saint_germain', 19, 'rw').
calciatore('marc_bartra', 81, 'spain', 'trabzonspor', 3, 'cb').
calciatore('felipe', 81, 'brazil', 'atletico_de_madrid', 18, 'cb').
calciatore('h_maguire', 81, 'england', 'manchester_united', 5, 'cb').
calciatore('heberto_gaucho', 81, 'brazil', 'clube_atletico_mineiro', 19, 'cb').
calciatore('oswaldinato', 81, 'brazil', 'flamengo', 9, 'st').
calciatore('nailton_padrenda', 81, 'brazil', 'clube_atletico_mineiro', 11, 'cam').
calciatore('welington_dano', 81, 'brazil', 'clube_atletico_mineiro', 21, 'lb').
calciatore('adriano_bisesi', 81, 'brazil', 'rb_bragantino', 21, 'st').
calciatore('rosival_dourado', 81, 'brazil', 'sport_club_corinthians_paulista', 5, 'cdm').
calciatore('adryan_zonta', 81, 'brazil', 'rb_bragantino', 10, 'lwb').
calciatore('g_mancini', 81, 'italy', 'roma', 23, 'cb').
calciatore('g_rodriguez', 81, 'argentina', 'real_betis_balompie', 5, 'cdm').
calciatore('d_upamecano', 81, 'france', 'fc_bayern_munchen', 2, 'cb').
calciatore('palhinha', 81, 'portugal', 'fulham', 26, 'cb').
calciatore('d_zakaria', 81, 'switzerland', 'chelsea', 20, 'cdm').
calciatore('m_akanji', 81, 'switzerland', 'manchester_city', 25, 'cb').
calciatore('a_zambo_anguissa', 81, 'cameroon', 'napoli', 99, 'cdm').
calciatore('k_tierney', 81, 'scotland', 'arsenal', 3, 'lwb').
calciatore('m_rashford', 81, 'england', 'manchester_united', 10, 'st').
calciatore('richarlison', 81, 'brazil', 'tottenham_hotspur', 9, 'st').
calciatore('gabriel', 81, 'brazil', 'arsenal', 6, 'cb').
calciatore('h_mkhitaryan', 81, 'armenia', 'inter', 22, 'cam').
calciatore('n_otamendi', 81, 'argentina', 'sl_benfica', 30, 'cb').
calciatore('m_gotze', 81, 'germany', 'eintracht_frankfurt', 27, 'cam').
calciatore('c_smalling', 81, 'england', 'roma', 6, 'cb').
calciatore('n_pope', 81, 'england', 'newcastle_united', 22, 'gk').
calciatore('rafael_toloi', 81, 'italy', 'atalanta', 2, 'cb').
calciatore('e_cavani', 81, 'uruguay', 'valencia_cf', 7, 'st').
calciatore('e_banega', 81, 'argentina', 'al_shabab', 10, 'cm').
calciatore('adan', 81, 'spain', 'sporting_cp', 1, 'gk').
calciatore('g_bale', 81, 'wales', 'los_angeles_fc', 11, 'st').
calciatore('j_vertonghen', 81, 'belgium', 'rsc_anderlecht', 14, 'cb').
calciatore('c_vela', 81, 'mexico', 'los_angeles_fc', 10, 'rw').
calciatore('joao_moutinho', 81, 'portugal', 'wolverhampton_wanderers', 28, 'cm').
calciatore('pepe', 81, 'portugal', 'fc_porto', 3, 'cb').
calciatore('g_lo_celso', 81, 'argentina', 'villarreal_cf', 17, 'cam').
calciatore('oscar', 81, 'brazil', 'shanghai_port_fc', 8, 'cam').
calciatore('j_gomez', 81, 'england', 'liverpool', 2, 'cb').
calciatore('jose_sa', 81, 'portugal', 'wolverhampton_wanderers', 1, 'gk').
calciatore('borja_iglesias', 81, 'spain', 'real_betis_balompie', 9, 'st').
calciatore('j_ward_prowse', 81, 'england', 'southampton', 8, 'cm').
calciatore('l_ocampos', 81, 'argentina', 'ajax', 11, 'rw').
calciatore('e_visca', 81, 'bosnia_and_herzegovina', 'trabzonspor', 7, 'rm').
calciatore('t_savanier', 81, 'france', 'montpellier_herault_sc', 11, 'cam').
calciatore('e_forsberg', 81, 'sweden', 'rb_leipzig', 10, 'cam').
calciatore('lucas_vazquez', 81, 'spain', 'real_madrid_cf', 17, 'rb').
calciatore('g_laborde', 81, 'france', 'ogc_nice', 24, 'st').
calciatore('j_hofmann', 81, 'germany', 'borussia_monchengladbach', 23, 'cam').
calciatore('n_tagliafico', 81, 'argentina', 'olympique_lyonnais', 3, 'lb').
calciatore('k_demirbay', 81, 'germany', 'bayer_04_leverkusen', 10, 'cm').
calciatore('o_vlachodimos', 81, 'greece', 'sl_benfica', 99, 'gk').
calciatore('v_grifo', 81, 'italy', 'sport_club_freiburg', 32, 'lm').
calciatore('r_andrich', 81, 'germany', 'bayer_04_leverkusen', 8, 'cdm').
calciatore('r_le_normand', 81, 'france', 'real_sociedad', 24, 'cb').
calciatore('ricardo_horta', 81, 'portugal', 'sc_braga', 21, 'cf').
calciatore('s_lobotka', 81, 'slovakia', 'napoli', 68, 'cm').
calciatore('k_phillips', 81, 'england', 'manchester_city', 4, 'cdm').
calciatore('m_uribe', 81, 'colombia', 'fc_porto', 8, 'cm').
calciatore('l_torreira', 81, 'uruguay', 'galatasaray_sk', 5, 'cdm').
calciatore('m_pasalic', 81, 'croatia', 'atalanta', 88, 'cam').
calciatore('n_keita', 81, 'guinea', 'liverpool', 8, 'cam').
calciatore('c_tolisso', 81, 'france', 'olympique_lyonnais', 88, 'cm').
calciatore('h_lozano', 81, 'mexico', 'napoli', 11, 'rw').
calciatore('m_politano', 81, 'italy', 'napoli', 21, 'rw').
calciatore('a_saint_maximin', 81, 'france', 'newcastle_united', 10, 'cam').
calciatore('s_fofana', 81, 'cote_divoire', 'racing_club_de_lens', 8, 'cm').
calciatore('inaki_williams', 81, 'ghana', 'athletic_club_de_bilbao', 9, 'st').
calciatore('j_musso', 81, 'argentina', 'atalanta', 1, 'gk').
calciatore('b_bourigeaud', 81, 'france', 'stade_rennais_fc', 14, 'rw').
calciatore('y_en_nesyri', 80, 'morocco', 'sevilla_fc', 15, 'st').
calciatore('javi_galan', 80, 'spain', 'rc_celta_de_vigo', 17, 'lb').
calciatore('f_neuhaus', 80, 'germany', 'borussia_monchengladbach', 32, 'cm').
calciatore('h_barnes', 80, 'england', 'leicester_city', 7, 'cam').
calciatore('a_isak', 80, 'sweden', 'newcastle_united', 14, 'st').
calciatore('l_sinisterra', 80, 'colombia', 'leeds_united', 23, 'lw').
calciatore('x_schlager', 80, 'austria', 'rb_leipzig', 24, 'cdm').
calciatore('d_kamada', 80, 'japan', 'eintracht_frankfurt', 15, 'cam').
calciatore('m_arambarri', 80, 'uruguay', 'getafe_cf', 18, 'cdm').
calciatore('a_lafont', 80, 'france', 'fc_nantes', 1, 'gk').
calciatore('maikel_catarino', 80, 'brazil', 'sport_club_corinthians_paulista', 4, 'rb').
calciatore('renato_sanches', 80, 'portugal', 'paris_saint_germain', 18, 'cam').
calciatore('arthur', 80, 'brazil', 'liverpool', 29, 'cm').
calciatore('tony_abranjes', 80, 'brazil', 'internacional', 3, 'cb').
calciatore('laure_santeiro', 80, 'brazil', 'fluminense', 9, 'cam').
calciatore('heniton_pires', 80, 'brazil', 'flamengo', 1, 'gk').
calciatore('m_guendouzi', 80, 'france', 'olympique_de_marseille', 6, 'cdm').
calciatore('l_bailey', 80, 'jamaica', 'aston_villa', 31, 'cam').
calciatore('a_wan_bissaka', 80, 'england', 'manchester_united', 29, 'rb').
calciatore('d_sow', 80, 'switzerland', 'eintracht_frankfurt', 8, 'cm').
calciatore('mario_hermoso', 80, 'spain', 'atletico_de_madrid', 22, 'cb').
calciatore('d_calabria', 80, 'italy', 'ac_milan', 2, 'rb').
calciatore('e_alvarez', 80, 'mexico', 'ajax', 4, 'cb').
calciatore('t_koopmeiners', 80, 'netherlands', 'atalanta', 7, 'cm').
calciatore('b_kamara', 80, 'france', 'aston_villa', 44, 'cdm').
calciatore('v_tsygankov', 80, 'ukraine', 'dynamo_kyiv', 15, 'cam').
calciatore('m_dmitrovic', 80, 'serbia', 'sevilla_fc', 1, 'gk').
calciatore('i_mcadoo', 80, 'england', 'afc_richmond', 5, 'cb').
calciatore('j_frimpong', 80, 'netherlands', 'bayer_04_leverkusen', 30, 'rm').
calciatore('nuno_mendes', 80, 'portugal', 'paris_saint_germain', 25, 'lb').
calciatore('s_botman', 80, 'netherlands', 'newcastle_united', 4, 'cb').
calciatore('j_timber', 80, 'netherlands', 'ajax', 2, 'cb').
calciatore('renan_lodi', 80, 'brazil', 'nottingham_forest', 32, 'lwb').
calciatore('reguilon', 80, 'spain', 'atletico_de_madrid', 3, 'lwb').
calciatore('v_coufal', 80, 'czech_republic', 'west_ham_united', 5, 'rb').
calciatore('a_rrahmani', 80, 'kosovo', 'napoli', 13, 'cb').
calciatore('s_mctominay', 80, 'scotland', 'manchester_united', 39, 'cdm').
calciatore('l_majer', 80, 'croatia', 'stade_rennais_fc', 21, 'cam').
calciatore('w_saliba', 80, 'france', 'arsenal', 12, 'cb').
calciatore('d_livakovic', 80, 'croatia', 'dinamo_zagreb', 40, 'gk').
calciatore('r_baku', 80, 'germany', 'vfl_wolfsburg', 20, 'rm').
calciatore('n_gonzalez', 80, 'argentina', 'fiorentina', 22, 'lm').
calciatore('e_smith_rowe', 80, 'england', 'arsenal', 10, 'cam').
calciatore('j_clauss', 80, 'france', 'olympique_de_marseille', 7, 'rwb').
calciatore('w_mckennie', 80, 'united_states', 'juventus', 8, 'cm').
calciatore('n_milenkovic', 80, 'serbia', 'fiorentina', 4, 'cb').
calciatore('n_aguerd', 80, 'morocco', 'west_ham_united', 27, 'cb').
calciatore('nelson_semedo', 80, 'portugal', 'wolverhampton_wanderers', 22, 'rwb').
calciatore('c_aranguiz', 80, 'chile', 'bayer_04_leverkusen', 20, 'cdm').
calciatore('lucas_moura', 80, 'brazil', 'tottenham_hotspur', 27, 'rw').
calciatore('jonathan_viera', 80, 'spain', 'union_deportiva_las_palmas', 21, 'cam').
calciatore('danilo', 80, 'brazil', 'juventus', 6, 'rb').
calciatore('sergi_roberto', 80, 'spain', 'fc_barcelona', 20, 'rb').
calciatore('allan', 80, 'brazil', 'everton', 6, 'cdm').
calciatore('j_cillessen', 80, 'netherlands', 'nec_nijmegen', 22, 'gk').
calciatore('h_vanaken', 80, 'belgium', 'club_brugge_kv', 20, 'cm').
calciatore('s_ortega', 80, 'germany', 'manchester_city', 18, 'gk').
calciatore('danilo_pereira', 80, 'portugal', 'paris_saint_germain', 15, 'cdm').
calciatore('morata', 80, 'spain', 'atletico_de_madrid', 19, 'st').
calciatore('l_shaw', 80, 'england', 'manchester_united', 23, 'lb').
calciatore('c_biraghi', 80, 'italy', 'fiorentina', 3, 'lb').
calciatore('e_dier', 80, 'england', 'tottenham_hotspur', 15, 'cb').
calciatore('deulofeu', 80, 'spain', 'udinese_calcio', 10, 'rw').
calciatore('t_hazard', 80, 'belgium', 'borussia_dortmund', 10, 'lm').
calciatore('t_vaclik', 80, 'czech_republic', 'free_agent', -, 'gk').
calciatore('edgar_badia', 80, 'spain', 'elche_cf', 13, 'gk').
calciatore('k_zouma', 80, 'france', 'west_ham_united', 4, 'cb').
calciatore('m_sabitzer', 80, 'austria', 'fc_bayern_munchen', 18, 'cm').
calciatore('k_kampl', 80, 'slovenia', 'rb_leipzig', 44, 'cm').
calciatore('a_delort', 80, 'algeria', 'ogc_nice', 7, 'st').
calciatore('b_leno', 80, 'germany', 'fulham', 17, 'gk').
calciatore('alex_sandro', 80, 'brazil', 'juventus', 12, 'lb').
calciatore('yeray', 80, 'spain', 'athletic_club_de_bilbao', 5, 'cb').
calciatore('g_ochoa', 80, 'mexico', 'free_agent', -, 'gk').
calciatore('h_herrera', 80, 'mexico', 'houston_dynamo', 16, 'cm').
calciatore('a_consigli', 80, 'italy', 'us_sassuolo_calcio', 47, 'gk').
calciatore('raul_garcia', 80, 'spain', 'athletic_club_de_bilbao', 22, 'cm').
calciatore('jose_fonte', 80, 'portugal', 'losc_lille', 6, 'cb').
calciatore('m_hamsik', 80, 'slovakia', 'trabzonspor', 17, 'cm').
calciatore('a_candreva', 80, 'italy', 'us_salernitana_1919', 87, 'rm').
calciatore('s_mignolet', 80, 'belgium', 'club_brugge_kv', 22, 'gk').
calciatore('joselu', 80, 'spain', 'rcd_espanyol_de_barcelona', 9, 'st').
calciatore('d_ospina', 80, 'colombia', 'al_nassr', 41, 'gk').
calciatore('e_capoue', 80, 'france', 'villarreal_cf', 6, 'cm').
calciatore('g_wijnaldum', 80, 'netherlands', 'roma', 25, 'cm').
calciatore('m_kruse', 80, 'germany', 'vfl_wolfsburg', 9, 'cam').
calciatore('m_darmian', 80, 'italy', 'inter', 36, 'rwb').
calciatore('f_coquelin', 80, 'france', 'villarreal_cf', 19, 'cm').
calciatore('d_blind', 80, 'netherlands', 'ajax', 17, 'cdm').
calciatore('a_cragno', 80, 'italy', 'ac_monza', 89, 'gk').
calciatore('r_freuler', 80, 'switzerland', 'nottingham_forest', 23, 'cm').
calciatore('m_arnold', 80, 'germany', 'vfl_wolfsburg', 27, 'cm').
calciatore('v_lindelof', 80, 'sweden', 'manchester_united', 2, 'cdm').
calciatore('alex_moreno', 80, 'spain', 'real_betis_balompie', 15, 'lb').
calciatore('m_dahoud', 80, 'germany', 'borussia_dortmund', 8, 'cm').
calciatore('j_ledesma', 80, 'argentina', 'cadiz_cf', 1, 'gk').
calciatore('h_traore', 80, 'mali', 'stade_rennais_fc', 27, 'rb').
calciatore('a_rebic', 80, 'croatia', 'ac_milan', 12, 'st').
calciatore('h_hateboer', 80, 'netherlands', 'atalanta', 33, 'rwb').
calciatore('kepa', 80, 'spain', 'chelsea', 1, 'gk').
calciatore('d_calvert_lewin', 80, 'england', 'everton', 9, 'st').
calciatore('l_klostermann', 80, 'germany', 'rb_leipzig', 16, 'rb').
calciatore('j_correa', 80, 'argentina', 'inter', 11, 'rw').
calciatore('r_karsdorp', 80, 'netherlands', 'roma', 2, 'rwb').
calciatore('joan_jordan', 80, 'spain', 'sevilla_fc', 8, 'cm').
calciatore('j_bowen', 80, 'england', 'west_ham_united', 20, 'lm').
calciatore('alex_berenguer', 80, 'spain', 'athletic_club_de_bilbao', 7, 'rm').
calciatore('s_bergwijn', 80, 'netherlands', 'ajax', 7, 'cam').
calciatore('e_buendia', 80, 'argentina', 'aston_villa', 10, 'cam').
calciatore('u_cakir', 80, 'turkey', 'trabzonspor', 1, 'gk').
calciatore('g_scamacca', 80, 'italy', 'west_ham_united', 7, 'st').
calciatore('morales', 80, 'spain', 'villarreal_cf', 22, 'lm').
calciatore('m_dubravka', 80, 'slovakia', 'manchester_united', 31, 'gk').
calciatore('w_benitez', 80, 'argentina', 'psv', 1, 'gk').
calciatore('l_paredes', 80, 'argentina', 'juventus', 32, 'cdm').
calciatore('s_azmoun', 80, 'iran', 'bayer_04_leverkusen', 9, 'st').
calciatore('william_carvalho', 80, 'portugal', 'real_betis_balompie', 14, 'cdm').
calciatore('b_cristante', 80, 'italy', 'roma', 4, 'cm').
calciatore('saul', 80, 'spain', 'atletico_de_madrid', 17, 'cm').
calciatore('m_de_roon', 80, 'netherlands', 'atalanta', 15, 'cb').
calciatore('a_belotti', 80, 'italy', 'roma', 11, 'st').
calciatore('fred', 80, 'brazil', 'manchester_united', 17, 'cm').
calciatore('c_gunter', 80, 'germany', 'sport_club_freiburg', 30, 'lb').
calciatore('a_rabiot', 80, 'france', 'juventus', 25, 'cm').
calciatore('rui_silva', 80, 'portugal', 'real_betis_balompie', 13, 'gk').
calciatore('a_romagnoli', 80, 'italy', 'lazio', 13, 'cb').
