calciatore(h_kane, st, 89).
calciatore(t_alexander_arnold, rb, 87).
calciatore(r_sterling, lw, 86).
calciatore(r_sterling, rw, 86).
calciatore(k_walker, rb, 85).
calciatore(j_vardy, st, 85).
calciatore(p_foden, lw, 85).
calciatore(p_foden, cf, 85).
calciatore(p_foden, cam, 85).
calciatore(j_grealish, lw, 84).
calciatore(j_grealish, lm, 84).
calciatore(j_grealish, cam, 84).
calciatore(k_trippier, rb, 84).
calciatore(k_trippier, rm, 84).
calciatore(j_bellingham, cm, 84).
calciatore(j_bellingham, lm, 84).
calciatore(j_tartt, st, 84).
calciatore(r_james, rwb, 84).
calciatore(r_james, rb, 84).
calciatore(d_rice, cdm, 84).
calciatore(m_mount, cam, 84).
calciatore(m_mount, rw, 84).
calciatore(j_sancho, lw, 84).
calciatore(j_sancho, rw, 84).
calciatore(j_sancho, lm, 84).
calciatore(f_tomori, cb, 84).
calciatore(r_kent, cdm, 83).
calciatore(r_kent, cm, 83).
calciatore(j_henderson, cm, 83).
calciatore(j_henderson, cdm, 83).
calciatore(j_stones, cb, 83).
calciatore(j_maddison, cam, 82).
calciatore(j_maddison, rm, 82).
calciatore(t_abraham, st, 82).
calciatore(b_saka, rm, 82).
calciatore(b_saka, lm, 82).
calciatore(a_ramsdale, gk, 82).
calciatore(b_chilwell, lwb, 82).
calciatore(b_chilwell, lb, 82).
calciatore(j_pickford, gk, 82).
calciatore(h_maguire, cb, 81).
calciatore(m_rashford, lw, 81).
calciatore(m_rashford, st, 81).
calciatore(c_smalling, cb, 81).
calciatore(n_pope, gk, 81).
calciatore(j_gomez, cb, 81).
calciatore(j_gomez, rb, 81).
calciatore(j_ward_prowse, cm, 81).
calciatore(k_phillips, cdm, 81).
calciatore(k_phillips, cm, 81).
calciatore(h_barnes, lm, 80).
calciatore(h_barnes, lw, 80).
calciatore(a_wan_bissaka, rb, 80).
calciatore(i_mcadoo, cb, 80).
calciatore(e_smith_rowe, lm, 80).
calciatore(e_smith_rowe, cam, 80).
calciatore(l_shaw, lb, 80).
calciatore(e_dier, cb, 80).
calciatore(d_calvert_lewin, st, 80).
calciatore(j_bowen, rm, 80).
calciatore(j_bowen, st, 80).
calciatore(c_gallagher, cm, 79).
calciatore(g_goodman, lb, 79).
calciatore(m_bumbercatch, cm, 79).
calciatore(m_bumbercatch, cdm, 79).
calciatore(m_bumbercatch, cam, 79).
calciatore(e_konsa, cb, 79).
calciatore(b_white, cb, 79).
calciatore(d_henderson, gk, 79).
calciatore(j_tarkowski, cb, 79).
calciatore(c_coady, cb, 79).
calciatore(l_dunk, cb, 79).
calciatore(c_wilson, st, 79).
calciatore(d_ings, st, 79).
calciatore(m_keane, cb, 79).
calciatore(a_dixon, rb, 78).
calciatore(c_hudson_odoi, lm, 78).
calciatore(c_hudson_odoi, rm, 78).
calciatore(c_hudson_odoi, rwb, 78).
calciatore(m_guehi, cb, 78).
calciatore(c_dawson, cb, 78).
calciatore(b_mee, cb, 78).
calciatore(a_cresswell, lb, 78).
calciatore(a_cresswell, cb, 78).
calciatore(p_bamford, st, 78).
calciatore(j_lingard, cam, 78).
calciatore(j_milner, cm, 78).
calciatore(j_milner, lb, 78).
calciatore(j_milner, rb, 78).
calciatore(j_tavernier, rb, 78).
calciatore(o_watkins, st, 78).
calciatore(o_watkins, lw, 78).
calciatore(m_edwards, rw, 78).
calciatore(m_edwards, lw, 78).
calciatore(k_walker_peters, rb, 78).
calciatore(k_walker_peters, lb, 78).
calciatore(t_mings, cb, 78).
calciatore(a_oxlade_chamberlain, cm, 77).
calciatore(d_burn, cb, 77).
calciatore(d_burn, lb, 77).
calciatore(i_toney, st, 77).
calciatore(j_harrison, lm, 77).
calciatore(j_harrison, rm, 77).
calciatore(d_alli, cam, 77).
calciatore(d_alli, cm, 77).
calciatore(m_targett, lb, 77).
calciatore(d_gray, lm, 77).
calciatore(d_gray, lw, 77).
calciatore(d_gray, cam, 77).
calciatore(j_shelvey, cm, 77).
calciatore(j_shelvey, cdm, 77).
calciatore(m_kilman, cb, 77).
calciatore(n_madueke, rw, 77).
calciatore(o_skipp, cdm, 77).
calciatore(o_skipp, cm, 77).
calciatore(a_lookman, lm, 77).
calciatore(a_lookman, rm, 77).
calciatore(r_holding, cb, 77).
calciatore(s_mavididi, lm, 77).
calciatore(s_mavididi, st, 77).
calciatore(b_godfrey, cb, 77).
calciatore(b_godfrey, lb, 77).
calciatore(j_justin, lb, 76).
calciatore(j_justin, rb, 76).
calciatore(t_chalobah, cb, 76).
calciatore(t_chalobah, cdm, 76).
calciatore(t_chalobah, cm, 76).
calciatore(r_loftus_cheek, cm, 76).
calciatore(r_loftus_cheek, rm, 76).
calciatore(r_barkley, cam, 76).
calciatore(r_barkley, cm, 76).
calciatore(a_townsend, rm, 76).
calciatore(h_winks, cm, 76).
calciatore(h_winks, cdm, 76).
calciatore(a_westwood, cdm, 76).
calciatore(a_westwood, cm, 76).
calciatore(e_eze, cam, 76).
calciatore(e_eze, cm, 76).
calciatore(e_eze, lm, 76).
calciatore(r_oxford, cb, 76).
calciatore(r_oxford, cdm, 76).
calciatore(r_oxford, rb, 76).
calciatore(r_kent, lw, 76).
calciatore(t_mitchell, lb, 76).
calciatore(c_jones, cm, 76).
calciatore(d_mcneil, lm, 76).
calciatore(d_mcneil, rm, 76).
calciatore(a_webster, cb, 76).
calciatore(j_hart, gk, 76).
calciatore(f_forster, gk, 76).
calciatore(j_lascelles, cb, 75).
calciatore(t_livramento, rb, 75).
calciatore(t_livramento, rwb, 75).
calciatore(c_taylor, lb, 75).
calciatore(k_hause, cb, 75).
