calciatore(m_neuer, gk, 90).
calciatore(j_kimmich, cdm, 89).
calciatore(j_kimmich, rb, 89).
calciatore(m_ter_stegen, gk, 88).
calciatore(t_kroos, cm, 88).
calciatore(a_rudiger, cb, 87).
calciatore(t_muller, cam, 87).
calciatore(t_muller, cf, 87).
calciatore(l_goretzka, cm, 87).
calciatore(l_goretzka, cdm, 87).
calciatore(k_trapp, gk, 86).
calciatore(n_sule, cb, 85).
calciatore(n_sule, rb, 85).
calciatore(s_gnabry, rm, 85).
calciatore(i_gundogan, cm, 85).
calciatore(i_gundogan, cdm, 85).
calciatore(m_reus, cam, 85).
calciatore(m_reus, cf, 85).
calciatore(m_reus, rm, 85).
calciatore(m_hummels, cb, 84).
calciatore(m_hummels, rb, 84).
calciatore(m_hummels, rw, 84).
calciatore(l_sane, lm, 84).
calciatore(k_havertz, cam, 84).
calciatore(k_havertz, cf, 84).
calciatore(k_havertz, st, 84).
calciatore(o_baumann, gk, 83).
calciatore(r_gosens, lwb, 82).
calciatore(r_gosens, lm, 82).
calciatore(j_tah, cb, 82).
calciatore(e_can, cm, 82).
calciatore(e_can, cb, 82).
calciatore(e_can, cdm, 82).
calciatore(j_brandt, cam, 82).
calciatore(j_brandt, cm, 82).
calciatore(j_brandt, rm, 82).
calciatore(t_werner, st, 82).
calciatore(t_werner, lw, 82).
calciatore(m_ginter, cb, 82).
calciatore(f_wirtz, cam, 82).
calciatore(f_wirtz, cm, 82).
calciatore(n_schlotterbeck, cb, 82).
calciatore(k_volland, st, 82).
calciatore(k_volland, cf, 82).
calciatore(k_volland, cam, 82).
calciatore(d_raum, lwb, 81).
calciatore(d_raum, lm, 81).
calciatore(d_raum, lb, 81).
calciatore(j_musiala, cm, 81).
calciatore(j_musiala, lm, 81).
calciatore(j_musiala, cam, 81).
calciatore(m_gotze, cam, 81).
calciatore(m_gotze, st, 81).
calciatore(m_gotze, cm, 81).
calciatore(j_hofmann, cam, 81).
calciatore(j_hofmann, rm, 81).
calciatore(j_hofmann, lm, 81).
calciatore(k_demirbay, cm, 81).
calciatore(k_demirbay, cdm, 81).
calciatore(k_demirbay, cam, 81).
calciatore(r_andrich, cdm, 81).
calciatore(r_andrich, cm, 81).
calciatore(f_neuhaus, cm, 80).
calciatore(r_baku, rm, 80).
calciatore(r_baku, rb, 80).
calciatore(r_baku, cm, 80).
calciatore(s_ortega, gk, 80).
calciatore(b_leno, gk, 80).
calciatore(m_kruse, cf, 80).
calciatore(m_kruse, cam, 80).
calciatore(m_arnold, cdm, 80).
calciatore(m_arnold, cm, 80).
calciatore(m_dahoud, cm, 80).
calciatore(m_dahoud, cdm, 80).
calciatore(l_klostermann, cb, 80).
calciatore(l_klostermann, rwb, 80).
calciatore(c_gunter, lb, 80).
calciatore(c_gunter, lm, 80).
calciatore(c_gunter, lwb, 80).
calciatore(j_boateng, cb, 79).
calciatore(l_stindl, cam, 79).
calciatore(j_weigl, cm, 79).
calciatore(j_weigl, cdm, 79).
calciatore(k_bellarabi, rm, 79).
calciatore(k_bellarabi, rw, 79).
calciatore(j_draxler, lw, 79).
calciatore(j_draxler, cam, 79).
calciatore(m_riemann, gk, 79).
calciatore(m_ozil, cam, 78).
calciatore(m_ozil, rm, 78).
calciatore(m_halstenberg, cb, 78).
calciatore(m_halstenberg, lwb, 78).
calciatore(j_hector, lb, 78).
calciatore(j_hector, cdm, 78).
calciatore(a_nubel, gk, 78).
calciatore(s_rode, cdm, 78).
calciatore(s_rode, cm, 78).
calciatore(l_unnerstall, gk, 78).
calciatore(l_nmecha, st, 78).
calciatore(c_kramer, cdm, 77).
calciatore(d_demme, cdm, 77).
calciatore(d_demme, cm, 77).
calciatore(n_dorsch, cdm, 77).
calciatore(n_dorsch, cm, 77).
calciatore(p_max, lb, 77).
calciatore(m_friedrich, cb, 77).
calciatore(m_schwabe, gk, 77).
calciatore(p_gross, cm, 77).
calciatore(p_gross, rm, 77).
calciatore(d_undav, st, 77).
calciatore(b_henrichs, rwb, 77).
calciatore(b_henrichs, rm, 77).
calciatore(b_henrichs, cm, 77).
calciatore(s_serdar, cm, 77).
calciatore(s_serdar, cdm, 77).
calciatore(s_serdar, cam, 77).
calciatore(h_mukhtar, cf, 77).
calciatore(h_mukhtar, st, 77).
calciatore(h_mukhtar, cam, 77).
calciatore(m_wolf, rm, 77).
calciatore(m_wolf, rb, 77).
calciatore(t_hubers, cb, 76).
calciatore(f_muller, gk, 76).
calciatore(m_philipp, cf, 76).
calciatore(m_philipp, cam, 76).
calciatore(m_uth, cam, 76).
calciatore(m_uth, cf, 76).
calciatore(m_uth, st, 76).
calciatore(k_gunter, cb, 76).
calciatore(r_knoche, cb, 76).
calciatore(k_vogt, cb, 76).
calciatore(k_vogt, cdm, 76).
calciatore(t_baumgartl, cb, 76).
calciatore(r_koch, cb, 76).
calciatore(r_koch, cdm, 76).
calciatore(a_maier, cm, 76).
calciatore(a_maier, cdm, 76).
calciatore(n_amiri, cam, 76).
calciatore(n_amiri, cm, 76).
calciatore(t_kehrer, cb, 76).
calciatore(t_kehrer, rb, 76).
calciatore(g_promel, cm, 76).
calciatore(g_promel, cdm, 76).
calciatore(y_gerhardt, cm, 76).
calciatore(j_burkardt, st, 76).
calciatore(j_burkardt, cf, 76).
calciatore(j_burkardt, rw, 76).
calciatore(r_zentner, gk, 76).
calciatore(a_stach, cm, 76).
calciatore(a_stach, cdm, 76).
calciatore(d_kohr, cdm, 76).
calciatore(d_kohr, cm, 76).
calciatore(s_terodde, st, 76).
calciatore(b_schmitz, rb, 75).
calciatore(n_hofler, cdm, 75).
calciatore(n_hofler, cm, 75).
calciatore(s_ulreich, gk, 75).
calciatore(k_adeyemi, st, 75).
calciatore(s_bell, cb, 75).
calciatore(f_uduokhai, cb, 75).
calciatore(a_pieper, cb, 75).
calciatore(k_adeyemi, st, 75).
calciatore(l_waldschmidt, cf, 75).
calciatore(l_waldschmidt, st, 75).
calciatore(m_ducksch, st, 75).
calciatore(m_wittek, lwb, 75).
calciatore(d_geiger, cm, 75).
calciatore(k_wagner, lb, 75).
calciatore(k_wagner, lwb, 75).
calciatore(m_eggestein, cdm, 75).
calciatore(m_eggestein, cm, 75).
calciatore(a_knauff, rm, 75).
calciatore(a_knauff, lm, 75).
calciatore(w_anton, cb, 75).
calciatore(w_anton, cdm, 75).
