calciatore(g_donnarumma, gk, 88).
calciatore(m_verratti, cm, 87).
calciatore(m_verratti, cam, 87).
calciatore(c_immobile, st, 86).
calciatore(n_barella, cm, 86).
calciatore(jorginho, cm, 85).
calciatore(d_berardi, rm, 84).
calciatore(d_berardi, rw, 84).
calciatore(l_insigne, lw, 84).
calciatore(l_insigne, cf, 84).
calciatore(l_insigne, lm, 84).
calciatore(l_bonucci, cb, 84).
calciatore(g_chiellini, cb, 84).
calciatore(f_chiesa, lw, 84).
calciatore(s_tonali, cdm, 84).
calciatore(s_tonali, cm, 84).
calciatore(a_bastoni, cb, 84).
calciatore(l_pellegrini, cam, 84).
calciatore(l_pellegrini, cm, 84).
calciatore(g_di_lorenzo, rb, 82).
calciatore(m_locatelli, cdm, 82).
calciatore(m_locatelli, cm, 82).
calciatore(l_spinazzola, lwb, 82).
calciatore(l_spinazzola, lm, 82).
calciatore(f_acerbi, cb, 82).
calciatore(n_zaniolo, cf, 81).
calciatore(n_zaniolo, rw, 81).
calciatore(n_zaniolo, rm, 81).
calciatore(g_mancini, cb, 81).
calciatore(rafael_toloi, cb, 81).
calciatore(v_grifo, lm, 81).
calciatore(v_grifo, cf, 81).
calciatore(m_politano, rw, 81).
calciatore(m_politano, rm, 81).
calciatore(d_calabria, rb, 80).
calciatore(c_biraghi, lb, 80).
calciatore(a_consigli, gk, 80).
calciatore(a_candreva, rm, 80).
calciatore(a_candreva, cm, 80).
calciatore(m_darmian, rwb, 80).
calciatore(m_darmian, rm, 80).
calciatore(a_cragno, gk, 80).
calciatore(g_scamacca, st, 80).
calciatore(b_cristante, cdm, 80).
calciatore(b_cristante, cm, 80).
calciatore(a_belotti, st, 80).
calciatore(a_romagnoli, cb, 80).
calciatore(a_ogbonna, cb, 79).
calciatore(g_raspadori, cf, 79).
calciatore(g_raspadori, cam, 79).
calciatore(g_raspadori, lm, 79).
calciatore(g_buffon, gk, 79).
calciatore(m_lazzari, rb, 79).
calciatore(joao_pedro, st, 79).
calciatore(m_zaccagni, lw, 79).
calciatore(m_perin, gk, 79).
calciatore(m_silvestri, gk, 79).
calciatore(a_florenzi, rb, 79).
calciatore(d_zappacosta, lwb, 79).
calciatore(d_zappacosta, lm, 79).
calciatore(d_zappacosta, rm, 79).
calciatore(f_bernardeschi, rm, 79).
calciatore(f_bernardeschi, rw, 79).
calciatore(luiz_felipe, cb, 79).
calciatore(g_vicario, gk, 78).
calciatore(g_bonaventura, cm, 78).
calciatore(f_caputo, st, 78).
calciatore(p_gollini, gk, 78).
calciatore(m_kean, st, 78).
calciatore(m_kean, lw, 78).
calciatore(m_faraoni, rwb, 78).
calciatore(m_faraoni, rm, 78).
calciatore(a_meret, gk, 78).
calciatore(d_dambrosio, cb, 78).
calciatore(g_caprari, cf, 78).
calciatore(f_dimarco, lwb, 78).
calciatore(f_dimarco, lm, 78).
calciatore(f_dimarco, cb, 78).
calciatore(e_audero, gk, 78).
calciatore(s_sensi, cm, 78).
calciatore(s_sensi, cam, 78).
calciatore(g_maggiore, cm, 77).
calciatore(g_maggiore, cdm, 77).
calciatore(r_soriano, cam, 77).
calciatore(r_soriano, cm, 77).
calciatore(r_soriano, cf, 77).
calciatore(s_el_shaarawy, lw, 77).
calciatore(s_el_shaarawy, lm, 77).
calciatore(m_balotelli, st, 77).
calciatore(s_sirigu, gk, 77).
calciatore(d_frattesi, cm, 77).
calciatore(d_frattesi, cdm, 77).
calciatore(m_pessina, cam, 77).
calciatore(m_pessina, cm, 77).
calciatore(m_pessina, cf, 77).
calciatore(emerson, lb, 77).
calciatore(g_castrovilli, cm, 77).
calciatore(r_orsolini, cf, 76).
calciatore(r_orsolini, rw, 76).
calciatore(f_di_francesco, lw, 76).
calciatore(f_di_francesco, rw, 76).
calciatore(l_montipo, gk, 76).
calciatore(a_petagna, st, 76).
calciatore(r_saponara, lw, 76).
calciatore(p_terracciano, gk, 76).
calciatore(n_casale, cb, 76).
calciatore(i_provedel, gk, 76).
calciatore(m_de_sciglio, rb, 76).
calciatore(m_de_sciglio, lb, 76).
calciatore(r_sottil, lw, 76).
calciatore(r_sottil, rw, 76).
calciatore(t_pobega, cm, 76).
calciatore(l_pellegrini, lb, 76).
calciatore(l_pellegrini, lwb, 76).
calciatore(d_rugani, cb, 76).
calciatore(d_cataldi, cdm, 76).
calciatore(d_cataldi, cm, 76).
calciatore(r_gagliardini, cdm, 76).
calciatore(r_gagliardini, cm, 76).
calciatore(f_quagliarella, st, 76).
calciatore(l_de_silvestri, rwb, 76).
calciatore(l_de_silvestri, rm, 76).
calciatore(s_okaka, st, 76).
calciatore(d_caligiuri, rm, 75).
calciatore(d_caligiuri, rwb, 75).
calciatore(d_caligiuri, cm, 75).
calciatore(s_birindelli, rwb, 75).
calciatore(s_birindelli, rm, 75).
calciatore(s_birindelli, rb, 75).
calciatore(p_beruatto, lb, 75).
calciatore(a_brignoli, gk, 75).
calciatore(a_pinamonti, st, 75).
calciatore(m_di_gregorio, gk, 75).
calciatore(s_birindelli, rwb, 75).
calciatore(s_birindelli, rm, 75).
calciatore(s_birindelli, rb, 75).
calciatore(n_rovella, cm, 75).
calciatore(n_rovella, cdm, 75).
calciatore(f_gatti, cb, 75).
calciatore(d_criscito, cb, 75).
calciatore(d_criscito, lb, 75).
calciatore(d_criscito, lm, 75).
calciatore(r_mandragora, cm, 75).
calciatore(r_mandragora, cdm, 75).
calciatore(n_sansone, cam, 75).
calciatore(n_sansone, lw, 75).
calciatore(f_gatti, cb, 75).
calciatore(p_beruatto, lb, 75).
calciatore(g_pezzella, lb, 75).
calciatore(g_pezzella, lm, 75).
calciatore(g_pezzella, lwb, 75).
calciatore(m_carnesecchi, gk, 74).
calciatore(m_aramu, cam, 74).
calciatore(m_aramu, rw, 74).
