calciatore(v_van_dijk, cb, 90).
calciatore(f_de_jong, cm, 87).
calciatore(m_depay, cf, 85).
calciatore(m_depay, st, 85).
calciatore(m_depay, lw, 85).
calciatore(m_de_ligt, cb, 85).
calciatore(s_de_vrij, cb, 84).
calciatore(c_gakpo, lw, 83).
calciatore(a_danjuma, lm, 82).
calciatore(a_danjuma, st, 82).
calciatore(d_dumfries, rwb, 82).
calciatore(d_dumfries, rm, 82).
calciatore(s_berghuis, cam, 82).
calciatore(s_berghuis, rw, 82).
calciatore(t_koopmeiners, cm, 80).
calciatore(t_koopmeiners, cdm, 80).
calciatore(j_frimpong, rb, 80).
calciatore(j_frimpong, rwb, 80).
calciatore(s_botman, cb, 80).
calciatore(j_timber, cb, 80).
calciatore(j_timber, rb, 80).
calciatore(j_cillessen, gk, 80).
calciatore(g_wijnaldum, cm, 80).
calciatore(g_wijnaldum, cdm, 80).
calciatore(d_blind, cb, 80).
calciatore(d_blind, lb, 80).
calciatore(d_blind, cdm, 80).
calciatore(h_hateboer, rwb, 80).
calciatore(h_hateboer, rb, 80).
calciatore(h_hateboer, rm, 80).
calciatore(r_karsdorp, rwb, 80).
calciatore(r_karsdorp, rm, 80).
calciatore(r_karsdorp, rb, 80).
calciatore(s_bergwijn, lw, 80).
calciatore(s_bergwijn, rw, 80).
calciatore(m_de_roon, cdm, 80).
calciatore(m_de_roon, cm, 80).
calciatore(m_de_roon, cb, 80).
calciatore(m_flekken, gk, 80).
calciatore(t_malacia, lb, 79).
calciatore(r_gravenberch, cm, 79).
calciatore(w_weghorst, st, 79).
calciatore(d_van_de_beek, cm, 79).
calciatore(d_van_de_beek, cdm, 79).
calciatore(d_van_de_beek, cam, 79).
calciatore(d_malen, st, 79).
calciatore(d_malen, lm, 79).
calciatore(j_bijlow, gk, 79).
calciatore(o_wijndal, lb, 79).
calciatore(l_de_jong, st, 79).
calciatore(d_klaassen, cam, 79).
calciatore(d_klaassen, cm, 79).
calciatore(j_veerman, cm, 78).
calciatore(j_veerman, cdm, 78).
calciatore(j_veerman, cam, 78).
calciatore(n_lang, lw, 78).
calciatore(n_lang, rw, 78).
calciatore(n_lang, st, 78).
calciatore(n_ake, cb, 78).
calciatore(n_ake, lb, 78).
calciatore(j_veltman, cb, 78).
calciatore(j_veltman, rb, 78).
calciatore(j_veltman, rwb, 78).
calciatore(p_rosario, cdm, 78).
calciatore(p_rosario, cm, 78).
calciatore(p_rosario, cb, 78).
calciatore(k_rekik, cb, 77).
calciatore(k_rekik, lb, 77).
calciatore(r_bazoer, cm, 77).
calciatore(r_bazoer, cdm, 77).
calciatore(r_bazoer, cb, 77).
calciatore(j_maas, cb, 77).
calciatore(j_teze, cb, 77).
calciatore(j_teze, rb, 77).
calciatore(l_geertruida, rb, 77).
calciatore(l_geertruida, cb, 77).
calciatore(w_hoedt, cb, 76).
calciatore(m_bizot, gk, 76).
calciatore(t_vilhena, lm, 76).
calciatore(t_vilhena, cm, 76).
calciatore(b_dost, st, 76).
calciatore(p_van_aanholt, lb, 76).
calciatore(p_struijk, cb, 76).
calciatore(p_struijk, cdm, 76).
calciatore(j_kluivert, lw, 76).
calciatore(j_kluivert, lm, 76).
calciatore(j_kluivert, rm, 76).
calciatore(j_st_juste, cb, 76).
calciatore(j_st_juste, rb, 76).
calciatore(b_brobbey, st, 76).
calciatore(r_vormer, cm, 76).
calciatore(t_krul, gk, 76).
calciatore(j_gouweleeuw, cb, 75).
calciatore(p_schuurs, cb, 75).
calciatore(g_til, cam, 75).
calciatore(g_til, cm, 75).
calciatore(p_schuurs, cb, 75).
calciatore(m_boadu, st, 75).
calciatore(m_bakker, lb, 75).
calciatore(t_ouwejan, lb, 75).
calciatore(t_ouwejan, lwb, 75).
calciatore(g_til, cam, 75).
calciatore(g_til, cm, 75).
calciatore(b_martins_indi, cb, 75).
calciatore(a_el_ghazi, lw, 75).
calciatore(a_el_ghazi, rw, 75).
calciatore(j_clasie, cm, 75).
calciatore(j_clasie, cdm, 75).
calciatore(g_hamer, cm, 74).
calciatore(g_hamer, cdm, 74).
calciatore(l_fer, cdm, 74).
calciatore(l_fer, cm, 74).
calciatore(k_tete, rb, 74).
calciatore(d_de_wit, cam, 74).
calciatore(d_de_wit, cm, 74).
calciatore(m_van_ginkel, cm, 74).
calciatore(m_van_ginkel, cdm, 74).
calciatore(j_riedewald, cdm, 74).
calciatore(j_riedewald, cm, 74).
calciatore(d_doekhi, cb, 74).
calciatore(m_stekelenburg, gk, 74).
calciatore(j_schouten, cdm, 74).
calciatore(j_schouten, cm, 74).
calciatore(a_matusiwa, cdm, 74).
calciatore(a_matusiwa, cm, 74).
calciatore(d_bulthuis, cb, 74).
calciatore(j_toornstra, cm, 74).
calciatore(j_toornstra, cam, 74).
calciatore(a_obispo, cb, 74).
calciatore(b_van_den_boomen, cm, 74).
calciatore(b_van_den_boomen, cdm, 74).
calciatore(a_maher, cdm, 74).
calciatore(a_maher, cm, 74).
calciatore(b_ramselaar, cam, 74).
calciatore(j_piroe, st, 73).
calciatore(j_piroe, rw, 73).
calciatore(j_piroe, cam, 73).
calciatore(s_spierings, cdm, 73).
calciatore(s_spierings, cm, 73).
calciatore(b_schenkeveld, cb, 73).
calciatore(k_taylor, cm, 73).
calciatore(k_taylor, cdm, 73).
calciatore(t_fosu_mensah, rb, 73).
calciatore(t_fosu_mensah, cb, 73).
calciatore(j_zirkzee, st, 73).
calciatore(j_zirkzee, cam, 73).
calciatore(v_janssen, st, 73).
calciatore(d_zeefuik, rb, 73).
calciatore(d_sinkgraven, lb, 73).
calciatore(d_sinkgraven, cm, 73).
calciatore(x_simons, cam, 73).
calciatore(x_simons, cm, 73).
calciatore(x_simons, rw, 73).
calciatore(m_van_der_hoorn, cb, 73).
calciatore(n_viergever, cb, 73).
calciatore(j_hendrix, cdm, 73).
calciatore(j_hendrix, cm, 73).
calciatore(z_flemming, cam, 73).
calciatore(z_flemming, st, 73).
calciatore(d_rensch, rb, 73).
calciatore(d_rensch, lb, 73).
calciatore(m_ihattaren, cam, 73).
calciatore(m_ihattaren, rw, 73).
calciatore(k_strootman, cm, 73).
calciatore(k_strootman, cdm, 73).
calciatore(j_drommel, gk, 73).
calciatore(q_timber, cm, 72).
calciatore(q_timber, cdm, 72).
calciatore(q_timber, cam, 72).
calciatore(t_haye, cm, 72).
calciatore(t_haye, cdm, 72).
calciatore(m_van_bergen, rw, 72).
calciatore(m_van_bergen, st, 72).
calciatore(m_van_bergen, lw, 72).
calciatore(j_de_wijs, cb, 72).
