calciatore(rodri, cdm, 87).
calciatore(de_gea, gk, 87).
calciatore(thiago, cm, 86).
calciatore(parejo, cm, 86).
calciatore(a_laporte, cb, 86).
calciatore(jordi_alba, lb, 85).
calciatore(sergio_busquets, cdm, 85).
calciatore(iago_aspas, st, 85).
calciatore(gerard_moreno, st, 85).
calciatore(pedri, cm, 85).
calciatore(sergio_ramos, cb, 84).
calciatore(carvajal, rb, 84).
calciatore(canales, rm, 84).
calciatore(canales, cam, 84).
calciatore(canales, cdm, 84).
calciatore(muniain, lm, 84).
calciatore(muniain, cam, 84).
calciatore(oyarzabal, lw, 84).
calciatore(oyarzabal, rw, 84).
calciatore(marcos_llorente, cm, 84).
calciatore(marcos_llorente, rm, 84).
calciatore(marcos_llorente, rb, 84).
calciatore(angelino, lwb, 83).
calciatore(angelino, lm, 83).
calciatore(marco_asensio, rw, 83).
calciatore(merino, cm, 83).
calciatore(fabian, cm, 83).
calciatore(fabian, cdm, 83).
calciatore(unai_simon, gk, 83).
calciatore(carlos_soler, cm, 83).
calciatore(carlos_soler, rm, 83).
calciatore(carlos_soler, cdm, 83).
calciatore(pau_torres, cb, 83).
calciatore(jesus_navas, rb, 83).
calciatore(jesus_navas, rm, 83).
calciatore(pique, cb, 83).
calciatore(david_silva, cam, 83).
calciatore(david_silva, cm, 83).
calciatore(luis_alberto, cm, 83).
calciatore(koke, cm, 83).
calciatore(koke, cdm, 83).
calciatore(david_soria, gk, 82).
calciatore(gaya, lb, 82).
calciatore(gaya, lm, 82).
calciatore(grimaldo, lb, 82).
calciatore(grimaldo, lwb, 82).
calciatore(grimaldo, lm, 82).
calciatore(aritz_elustondo, cb, 82).
calciatore(aritz_elustondo, rb, 82).
calciatore(alex_remiro, gk, 82).
calciatore(dani_olmo, cam, 82).
calciatore(dani_olmo, cf, 82).
calciatore(ferran_torres, lw, 82).
calciatore(ferran_torres, st, 82).
calciatore(sergi_darder, cm, 82).
calciatore(sergi_darder, cdm, 82).
calciatore(sergi_darder, cam, 82).
calciatore(inigo_martinez, cb, 82).
calciatore(yuri_berchiche, lb, 82).
calciatore(azpilicueta, cb, 82).
calciatore(azpilicueta, rwb, 82).
calciatore(azpilicueta, rb, 82).
calciatore(raul_albiol, cb, 82).
calciatore(isco, cam, 82).
calciatore(isco, lw, 82).
calciatore(isco, cm, 82).
calciatore(nacho_fernandez, cb, 82).
calciatore(nacho_fernandez, lb, 82).
calciatore(pedro_porro, rwb, 81).
calciatore(pedro_porro, rm, 81).
calciatore(cucurella, lb, 81).
calciatore(cucurella, cb, 81).
calciatore(cucurella, lm, 81).
calciatore(pablo_sarabia, rw, 81).
calciatore(pablo_sarabia, cam, 81).
calciatore(pablo_sarabia, lw, 81).
calciatore(marc_bartra, cb, 81).
calciatore(adan, gk, 81).
calciatore(borja_iglesias, st, 81).
calciatore(lucas_vazquez, rb, 81).
calciatore(lucas_vazquez, rw, 81).
calciatore(javi_galan, lb, 80).
calciatore(mario_hermoso, cb, 80).
calciatore(mario_hermoso, lb, 80).
calciatore(reguilon, lwb, 80).
calciatore(reguilon, lb, 80).
calciatore(jonathan_viera, cam, 80).
calciatore(jonathan_viera, cm, 80).
calciatore(jonathan_viera, lm, 80).
calciatore(sergi_roberto, rb, 80).
calciatore(sergi_roberto, cm, 80).
calciatore(morata, st, 80).
calciatore(deulofeu, cf, 80).
calciatore(deulofeu, st, 80).
calciatore(edgar_badia, gk, 80).
calciatore(yeray, cb, 80).
calciatore(raul_garcia, st, 80).
calciatore(joselu, st, 80).
calciatore(alex_moreno, lb, 80).
calciatore(kepa, gk, 80).
calciatore(joan_jordan, cm, 80).
calciatore(joan_jordan, cdm, 80).
calciatore(alex_berenguer, rm, 80).
calciatore(alex_berenguer, lm, 80).
calciatore(morales, lm, 80).
calciatore(morales, st, 80).
calciatore(saul, cm, 80).
calciatore(saul, lm, 80).
calciatore(saul, lwb, 80).
calciatore(carles_gil, cam, 80).
calciatore(carles_gil, rm, 80).
calciatore(unai_nunez, cb, 79).
calciatore(luis_milla, cdm, 79).
calciatore(luis_milla, cm, 79).
calciatore(diego_lopez, gk, 79).
calciatore(ansu_fati, lw, 79).
calciatore(pedro, lw, 79).
calciatore(pedro, rw, 79).
calciatore(pedro, cf, 79).
calciatore(gavi, cm, 79).
calciatore(gavi, lw, 79).
calciatore(gavi, rw, 79).
calciatore(yeremy_pino, rm, 79).
calciatore(yeremy_pino, st, 79).
calciatore(zubimendi, cm, 79).
calciatore(zubimendi, cdm, 79).
calciatore(guaita, gk, 79).
calciatore(pablo_fornals, cam, 79).
calciatore(pablo_fornals, lm, 79).
calciatore(david_garcia, cb, 79).
calciatore(rafa_mir, st, 79).
calciatore(joaquin, rm, 79).
calciatore(joaquin, lm, 79).
calciatore(sergio_asenjo, gk, 79).
calciatore(fran_beltran, cdm, 79).
calciatore(fran_beltran, cm, 79).
calciatore(pau_lopez, gk, 79).
calciatore(suso, rw, 79).
calciatore(juanmi, lm, 79).
calciatore(juanmi, st, 79).
calciatore(marcos_alonso, lb, 79).
calciatore(marcos_alonso, lwb, 79).
calciatore(ander_herrera, cm, 79).
calciatore(ander_herrera, cdm, 79).
calciatore(hector_bellerin, rb, 79).
calciatore(adama_traore, rw, 79).
calciatore(adama_traore, lw, 79).
calciatore(ruben_garcia, lm, 79).
calciatore(ruben_garcia, cm, 79).
calciatore(ruben_garcia, cam, 79).
calciatore(jonny, lwb, 79).
calciatore(jonny, rwb, 79).
calciatore(manu_trigueros, cm, 79).
calciatore(manu_trigueros, lm, 79).
calciatore(manu_trigueros, rm, 79).
calciatore(denis_suarez, cm, 79).
calciatore(puado, lm, 78).
calciatore(puado, rm, 78).
calciatore(puado, st, 78).
calciatore(melendo, cam, 78).
calciatore(melendo, rm, 78).
calciatore(melendo, cm, 78).
calciatore(portu, rm, 78).
calciatore(portu, lm, 78).
calciatore(juan_bernat, lb, 78).
calciatore(victor_ruiz, cb, 78).
calciatore(mario_gaspar, rb, 78).
calciatore(ruben_pena, rb, 78).
calciatore(ruben_pena, rm, 78).
calciatore(ruben_pena, lb, 78).
